services:
  - type: web
    name: lhl-planner
    env: node
    buildCommand: pnpm install && pnpm --filter lhl-planner build
    startCommand: pnpm --filter lhl-planner start
    envVars:
      - key: DATABASE_URL
        fromSecret: DATABASE_URL  
