#!/usr/bin/env node
/**
 * Git Commit Message Debugger
 *
 * Validates commit messages against project conventions and prints detailed
 * diagnostic output so you can see exactly what passed, what failed, and why.
 *
 * Usage:
 *   # Debug a message string directly
 *   pnpm --filter @workspace/scripts run debug-commit -- --debug "Fix typo in README"
 *
 *   # Install as a git commit-msg hook (writes .git/hooks/commit-msg)
 *   pnpm --filter @workspace/scripts run debug-commit -- --install
 *
 *   # Run as a git hook (called automatically after install)
 *   .git/hooks/commit-msg .git/COMMIT_EDITMSG
 */

import { readFileSync, writeFileSync, chmodSync, existsSync } from "fs";
import { resolve } from "path";

// ── Types ─────────────────────────────────────────────────────────────────────

type Severity = "error" | "warning";

interface Rule {
  name: string;
  description: string;
  severity: Severity;
  check: (subject: string, body: string | null) => boolean;
  hint: string;
}

interface RuleResult {
  rule: Rule;
  passed: boolean;
}

// ── ANSI colours (gracefully disabled when not a TTY) ────────────────────────

const isTTY = process.stdout.isTTY;
const c = {
  reset: isTTY ? "\x1b[0m" : "",
  bold: isTTY ? "\x1b[1m" : "",
  dim: isTTY ? "\x1b[2m" : "",
  green: isTTY ? "\x1b[32m" : "",
  yellow: isTTY ? "\x1b[33m" : "",
  red: isTTY ? "\x1b[31m" : "",
  cyan: isTTY ? "\x1b[36m" : "",
};

// ── Rules ─────────────────────────────────────────────────────────────────────

const IMPERATIVE_BLOCKLIST = /^(added|fixed|updated|removed|changed|refactored|improved|cleaned|merged|reverted|bumped|initialized|implemented|enabled|disabled|replaced|extracted|created|renamed|deleted|moved|optimized|simplified|formatted|sorted|handled|configured|documented)/i;

const RULES: Rule[] = [
  {
    name: "subject-not-empty",
    description: "Subject line must not be empty",
    severity: "error",
    check: (subject) => subject.trim().length > 0,
    hint: "Write a short, descriptive subject line.",
  },
  {
    name: "subject-max-length",
    description: "Subject line must be ≤ 72 characters",
    severity: "error",
    check: (subject) => subject.trim().length <= 72,
    hint: `Current length: ${0}. Shorten it — move detail to the body.`,
  },
  {
    name: "subject-no-trailing-period",
    description: "Subject line must not end with a period",
    severity: "error",
    check: (subject) => !subject.trim().endsWith("."),
    hint: 'Remove the trailing "." — it wastes space and is not conventional.',
  },
  {
    name: "subject-no-wip",
    description: 'Subject must not start with "WIP" or "wip"',
    severity: "error",
    check: (subject) => !/^wip\b/i.test(subject.trim()),
    hint: "Finish the work before committing, or use a draft PR instead.",
  },
  {
    name: "subject-imperative-mood",
    description:
      "Subject should use imperative mood (Fix, Add, Remove… not Fixed, Adding…)",
    severity: "warning",
    check: (subject) => !IMPERATIVE_BLOCKLIST.test(subject.trim()),
    hint: 'Use present-tense imperative: "Fix bug" not "Fixed bug" or "Fixing bug".',
  },
  {
    name: "body-blank-separator",
    description: "If a body is present, there must be a blank line after the subject",
    severity: "error",
    check: (_subject, body) => {
      if (!body) return true;
      // body passed here already has the separator line stripped;
      // the raw check is done in parseMessage — if separator was missing we mark body as invalid
      return body !== "__MISSING_SEPARATOR__";
    },
    hint: "Add an empty line between the subject and the body.",
  },
  {
    name: "body-line-max-length",
    description: "Body lines should be ≤ 100 characters",
    severity: "warning",
    check: (_subject, body) => {
      if (!body || body === "__MISSING_SEPARATOR__") return true;
      return body.split("\n").every((line) => line.length <= 100);
    },
    hint: "Wrap long body lines at 100 characters for readability in terminals.",
  },
];

// ── Parser ────────────────────────────────────────────────────────────────────

interface ParsedMessage {
  raw: string;
  subject: string;
  body: string | null;
  isAutoGenerated: boolean;
}

function parseMessage(raw: string): ParsedMessage {
  // Strip comment lines (lines starting with #)
  const lines = raw.split("\n").filter((l) => !l.startsWith("#"));

  // Detect auto-generated messages (merge commits, amends) — skip validation
  const subject = lines[0] ?? "";
  const isAutoGenerated =
    /^Merge (branch|pull request|remote-tracking branch)/.test(subject) ||
    /^Revert "/.test(subject);

  if (lines.length <= 1) {
    return { raw, subject, body: null, isAutoGenerated };
  }

  // Check for blank separator line between subject and body
  const hasSeparator = lines[1] === "";
  if (!hasSeparator && lines.slice(1).some((l) => l.trim() !== "")) {
    return {
      raw,
      subject,
      body: "__MISSING_SEPARATOR__",
      isAutoGenerated,
    };
  }

  const bodyLines = lines.slice(2);
  const body = bodyLines.join("\n").trim() || null;

  return { raw, subject, body, isAutoGenerated };
}

// ── Validator ─────────────────────────────────────────────────────────────────

function validate(parsed: ParsedMessage): RuleResult[] {
  return RULES.map((rule) => ({
    rule,
    passed: rule.check(parsed.subject, parsed.body),
  }));
}

// ── Printer ───────────────────────────────────────────────────────────────────

function printReport(parsed: ParsedMessage, results: RuleResult[]): void {
  const errors = results.filter((r) => !r.passed && r.rule.severity === "error");
  const warnings = results.filter((r) => !r.passed && r.rule.severity === "warning");
  const passed = results.filter((r) => r.passed);

  console.log(`\n${c.bold}${c.cyan}╔══════════════════════════════════════════╗`);
  console.log(`║   Git Commit Message Debugger            ║`);
  console.log(`╚══════════════════════════════════════════╝${c.reset}\n`);

  // Show the message being analysed
  console.log(`${c.bold}Message:${c.reset}`);
  const subjectDisplay = parsed.subject.trim() || c.dim + "(empty)" + c.reset;
  console.log(`  ${c.bold}Subject:${c.reset} ${subjectDisplay}`);
  if (parsed.subject.trim().length > 0) {
    const len = parsed.subject.trim().length;
    const bar = len <= 50 ? c.green : len <= 72 ? c.yellow : c.red;
    console.log(`  ${c.dim}Length:  ${bar}${len}/72${c.reset}`);
  }
  if (parsed.body && parsed.body !== "__MISSING_SEPARATOR__") {
    const bodyPreview = parsed.body.split("\n").slice(0, 3).join("\n    ");
    console.log(`  ${c.bold}Body:${c.reset}\n    ${bodyPreview}`);
  }

  if (parsed.isAutoGenerated) {
    console.log(
      `\n${c.dim}ℹ  Auto-generated commit (merge/revert) — skipping validation.${c.reset}\n`
    );
    return;
  }

  console.log(`\n${c.bold}Rules:${c.reset}`);

  for (const { rule, passed: ok } of results) {
    const sev = rule.severity;
    const icon = ok ? `${c.green}✓${c.reset}` : sev === "error" ? `${c.red}✗${c.reset}` : `${c.yellow}⚠${c.reset}`;
    const label = ok ? `${c.green}PASS${c.reset}` : sev === "error" ? `${c.red}FAIL${c.reset}` : `${c.yellow}WARN${c.reset}`;
    console.log(`  ${icon} ${c.bold}${rule.name}${c.reset}  [${label}]`);
    console.log(`     ${c.dim}${rule.description}${c.reset}`);
    if (!ok) {
      console.log(`     ${c.yellow}→ ${rule.hint}${c.reset}`);
    }
  }

  // Summary
  console.log();
  if (errors.length === 0 && warnings.length === 0) {
    console.log(`${c.green}${c.bold}✅  All checks passed.${c.reset}\n`);
  } else if (errors.length > 0) {
    console.log(
      `${c.red}${c.bold}❌  ${errors.length} error(s), ${warnings.length} warning(s). Fix the errors before committing.${c.reset}\n`
    );
  } else {
    console.log(
      `${c.yellow}${c.bold}⚠   0 errors, ${warnings.length} warning(s). Commit will proceed, but consider the warnings.${c.reset}\n`
    );
  }

  // Stat line
  console.log(
    `${c.dim}Passed ${passed.length}/${results.length} rules  ·  ${errors.length} error(s)  ·  ${warnings.length} warning(s)${c.reset}\n`
  );
}

// ── Install helper ────────────────────────────────────────────────────────────

function installHook(): void {
  const repoRoot = resolve(process.cwd(), "..");
  const hookPath = resolve(repoRoot, ".git", "hooks", "commit-msg");
  const scriptPath = resolve(process.cwd(), "src", "git-commit-msg-debugger.ts");

  if (!existsSync(resolve(repoRoot, ".git"))) {
    console.error("Could not find .git directory. Run from the scripts package.");
    process.exit(1);
  }

  const hookContent = `#!/bin/sh
# Git commit-msg hook — installed by scripts/src/git-commit-msg-debugger.ts
cd "$(git rev-parse --show-toplevel)"
pnpm --filter @workspace/scripts exec tsx scripts/src/git-commit-msg-debugger.ts "$1"
`;

  writeFileSync(hookPath, hookContent, "utf8");
  chmodSync(hookPath, 0o755);
  console.log(`${c.green}✓${c.reset} Installed commit-msg hook at ${hookPath}`);
  console.log(
    `  It will run ${c.bold}tsx scripts/src/git-commit-msg-debugger.ts${c.reset} on every commit.`
  );
}

// ── Entry point ───────────────────────────────────────────────────────────────

function main(): void {
  const [, , ...rawArgs] = process.argv;
  // Strip the "--" separator that pnpm injects when using `pnpm run x -- ...`
  const args = rawArgs.filter((a) => a !== "--");

  if (args[0] === "--install") {
    installHook();
    return;
  }

  if (args[0] === "--debug") {
    const msg = args.slice(1).join(" ");
    if (!msg) {
      console.error('Usage: debug-commit --debug "your commit message"');
      process.exit(1);
    }
    const parsed = parseMessage(msg);
    const results = validate(parsed);
    printReport(parsed, results);
    const hasErrors = results.some((r) => !r.passed && r.rule.severity === "error");
    process.exit(hasErrors ? 1 : 0);
  }

  // Hook mode: first argument is the path to the commit-msg file
  if (args[0]) {
    let raw: string;
    try {
      raw = readFileSync(args[0], "utf8");
    } catch (err) {
      console.error(`Could not read commit message file: ${args[0]}`);
      process.exit(1);
    }
    const parsed = parseMessage(raw);
    const results = validate(parsed);
    printReport(parsed, results);
    const hasErrors =
      !parsed.isAutoGenerated &&
      results.some((r) => !r.passed && r.rule.severity === "error");
    process.exit(hasErrors ? 1 : 0);
  }

  // No args — show usage
  console.log(`
${c.bold}Git Commit Message Debugger${c.reset}

${c.bold}Usage:${c.reset}
  ${c.cyan}pnpm --filter @workspace/scripts run debug-commit -- --debug "Fix typo"${c.reset}
      Validate a message string and print a full diagnostic report.

  ${c.cyan}pnpm --filter @workspace/scripts run debug-commit -- --install${c.reset}
      Install this script as the repo's commit-msg git hook.

  ${c.cyan}tsx scripts/src/git-commit-msg-debugger.ts <msg-file>${c.reset}
      Hook mode: validate the file at <msg-file> (e.g. .git/COMMIT_EDITMSG).

${c.bold}Rules enforced:${c.reset}
${RULES.map((r) => `  ${r.severity === "error" ? c.red + "error  " : c.yellow + "warning"}${c.reset}  ${r.name}`).join("\n")}
`);
}

main();
